### ISSUE TITLE
Add maybeNull to imgUrl

### ISSUE THREAD

**Issue by valterbarros** [richiemccoll/visualising-front-end-performance-demo#2]
I had to add that to Launch type because I was getting an error from a null image from SpaceX API on before-fixes branch

```
types.maybeNull(types.string)
```

https://github.com/richiemccoll/visualising-front-end-performance-demo/blob/441335e9d1835f97c0a0da50c8d5355c183142ff/stores/launch.store.js#L25

**Comment by richiemccoll** [comment]
Awesome! Thanks for the heads up @valterbarros. I've pushed a fix to both `master` and `before-fixes` branches (https://github.com/richiemccoll/visualising-front-end-performance-demo/commit/849a9058e1954e52811560edd41671a2fdab794f) 👍

**Comment by valterbarros** [comment]
cool @richiemccoll
